export const Font = {
  regularH1_42: {
    fontSize: "clamp(2.5rem, 4vw, 3.5rem)",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 400,
    lineHeight: 1.05,
    letterSpacing: "-0.04em",
  },
  regularH2_35: {
    fontSize: "clamp(2rem, 3vw, 2.75rem)",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 400,
    lineHeight: 1.1,
    letterSpacing: "-0.03em",
  },
  regularH3_29: {
    fontSize: "clamp(1.6rem, 2.2vw, 2.15rem)",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 400,
    lineHeight: 1.15,
    letterSpacing: "-0.03em",
  },
  regularH4_24: {
    fontSize: "24px",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 400,
    lineHeight: 1.2,
    letterSpacing: "-0.02em",
  },
  regularH5_20: {
    fontSize: "20px",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 400,
    lineHeight: 1.3,
  },
  regular17: {
    fontSize: "18px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontWeight: 400,
    lineHeight: 1.6,
  },
  regular14: {
    fontSize: "16px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontWeight: 400,
    lineHeight: 1.55,
  },
  regular13: {
    fontSize: "14px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontWeight: 400,
    lineHeight: 1.5,
  },
  regular12: {
    fontSize: "12px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontWeight: 400,
    lineHeight: 1.45,
  },
  regular10: {
    fontSize: "10px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontWeight: 400,
    lineHeight: 1.4,
  },
  mediumH1_42: {
    fontSize: "clamp(2.5rem, 4vw, 3.5rem)",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 500,
    lineHeight: 1.05,
    letterSpacing: "-0.04em",
  },
  mediumH2_35: {
    fontSize: "clamp(2rem, 3vw, 2.75rem)",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 500,
    lineHeight: 1.1,
    letterSpacing: "-0.03em",
  },
  mediumH3_29: {
    fontSize: "clamp(1.6rem, 2.2vw, 2.15rem)",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 500,
    lineHeight: 1.15,
    letterSpacing: "-0.03em",
  },
  mediumH4_24: {
    fontSize: "24px",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 500,
    lineHeight: 1.2,
  },
  mediumH5_20: {
    fontSize: "20px",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 500,
    lineHeight: 1.3,
  },
  medium17: {
    fontSize: "18px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontWeight: 500,
    lineHeight: 1.55,
  },
  medium14: {
    fontSize: "16px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontWeight: 500,
    lineHeight: 1.5,
  },
  medium12: {
    fontSize: "12px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontWeight: 500,
    lineHeight: 1.45,
  },
  medium10: {
    fontSize: "10px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontWeight: 500,
    lineHeight: 1.4,
  },
  boldH1_42: {
    fontSize: "clamp(2.5rem, 4vw, 3.5rem)",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 700,
    lineHeight: 1.05,
    letterSpacing: "-0.04em",
  },
  boldH2_35: {
    fontSize: "clamp(2rem, 3vw, 2.75rem)",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 700,
    lineHeight: 1.1,
    letterSpacing: "-0.03em",
  },
  boldH3_29: {
    fontSize: "clamp(1.6rem, 2.2vw, 2.15rem)",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 700,
    lineHeight: 1.15,
    letterSpacing: "-0.03em",
  },
  boldH4_24: {
    fontSize: "24px",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 700,
    lineHeight: 1.2,
  },
  boldH5_20: {
    fontSize: "20px",
    fontFamily: 'var(--font-sans, "SF Pro Display", "Inter", sans-serif)',
    fontWeight: 700,
    lineHeight: 1.25,
  },
  bold17: {
    fontSize: "18px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontWeight: 700,
    lineHeight: 1.45,
  },
  bold14: {
    fontSize: "16px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontWeight: 700,
    lineHeight: 1.4,
  },
  bold12: {
    fontSize: "12px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontWeight: 700,
    lineHeight: 1.4,
  },
  bold10: {
    fontSize: "10px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontWeight: 700,
    lineHeight: 1.35,
  },
  italic12: {
    fontSize: "12px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontStyle: "italic",
    lineHeight: 1.45,
  },
  italic17: {
    fontSize: "18px",
    fontFamily: 'var(--font-sans, "SF Pro Text", "Inter", sans-serif)',
    fontStyle: "italic",
    lineHeight: 1.55,
  },
}
